### ISSUE TITLE
How to run test for projections?

### ISSUE THREAD

**Issue by laseryuan** [hicknhack-software/rails-disco-examples#2]
Don't know how to invoke the test: rails-disco-examples/disco_blog/test/projections/posts_projection_test.rb
I've tried "rake test" "rake test:projections"

**Comment by arBmind** [comment]
A good point. I never tried that... I ran the tests directly from Redmine.

Maybe we need to add a special Rake task for that...

**Comment by arBmind** [comment]
You can use `rake test:all` to run all tests that includes the projections.

I will try to add a `rake test:projections` as well.

**Comment by arBmind** [comment]
I added support for `rake test` and `rake test:projections` with hicknhack-software/rails-disco@143bccfb453159c5c3070c0853d1e579112240e4
