### ISSUE TITLE
Bundle install fails for disco_react

### ISSUE THREAD

**Issue by elg0nz** [hicknhack-software/rails-disco-examples#3]
There are some gems hardcoded on the gemfile.
i.e.

```
gem 'active_event', path: 'D:/arB/projects/eventsource/rails-disco/active_event'
```

https://github.com/hicknhack-software/rails-disco-examples/blob/0906ff73a8e38184ab7919da6a0f0d6394dd0922/disco_react/Gemfile

**Comment by arBmind** [comment]
Thank you for pointing this out. Fixed.

**Comment by elg0nz** [comment]
Thanks! This project is quite interesting. 
I recently did a similar experiment using Kafka for EventSourcing. I'll send you a link once it's open sourced.
